### ISSUE TITLE
Incorrect parsing of NBT

### ISSUE THREAD

**Issue by undead3141** [thisjaiden/golden_apple#1]
I don't know if this project is active yet, but I was collecting a bunch of NBT libraries for my benchmarks and noticed abnormal performance. It looks like this library does not read NBT correctly.
I briefly checked out the code and this is what I found:
- https://github.com/thisjaiden/golden_apple/blob/master/src/nbt.rs#L62 - [X; N] syntax repeats the value, not the expression, so this actually reads one byte and duplicates it.
- https://github.com/thisjaiden/golden_apple/blob/master/src/nbt.rs#L93 - the same mistake in this function.

**Comment by thisjaiden** [comment]
I've been working on getting back into this project-- I'll have a fix out by Monday!

**Comment by undead3141** [comment]
Awesome! I'll be waiting :)

**Comment by thisjaiden** [comment]
0.18.0 should fix this, though I'm not certain. I'll do some tests (and write some unit tests) tomorrow most likely.

**Comment by undead3141** [comment]
This perfectly valid nbt data: `[10, 0, 1, 65, 9, 0, 0, 1, 0, 0, 0, 1, 127, 0]`
results in an error: `InvalidNBTType`
because the implementation reads the tag id of tags inside of a list, which is incorrect. `TAG_List` is prefixed with a tag id, and all elements of the list are of that type.
https://wiki.vg/NBT#Specification:list_tag
https://github.com/thisjaiden/golden_apple/blob/master/src/nbt.rs#L112

**Comment by thisjaiden** [comment]
Fixed with latest push/update! I should probably do some cleanup and performance improvements, but it should at least work now!😅
